package site.arookieofc.service.BO;

public enum ActivityType {
    COMMUNITY_SERVICE,
    CULTURE_SERVICE,
    EMERGENCY_RESCUE,
    ANIMAL_PROTECTION,
    POVERTY_ASSISTANCE,
    ELDERLY_DISABLED_ASSISTANCE,
    MEDICAL_ASSISTANCE,
    ORPHAN_EDUCATION_ASSISTANCE
}
