input {
  tcp {
    port => 5000
    codec => json_lines
  }
}

filter {
  if ![service] {
    mutate {
      add_field => { "service" => "volunteer-duration" }
    }
  }
}

output {
  elasticsearch {
    hosts => ["http://${LS_ES_HOST:localhost}:${LS_ES_PORT:9200}"]
    index => "volunteer-duration-%{+YYYY.MM.dd}"
  }
  stdout {
    codec => rubydebug
  }
}
